### ISSUE TITLE
Initial prototype tracking

### ISSUE THREAD

**Issue by cwbeitel** [projectclarify/chrome-extension#1]
This issue will track progress on initial extension prototype, following on [this](https://github.com/projectclarify/community/blob/master/proposals/chrome-extension.md) proposal.

At a high level the following things are required:

- [ ] An extension exists and can be installed without error; displays an icon in the address bar.
- [ ] When the address bar icon is clicked, it displays a drop-down where users can configure both settings related to feedback as well as whether video data is collected at all.
- [ ] When enabled can obtain and query frame of user video against [Azure emotion API](https://azure.microsoft.com/en-us/services/cognitive-services/emotion/) and store time-stamped response data in local storage.
- [ ] Asynchronously another function periodically obtains data from local storage and computes what cue to provide; initially this can be as simple as varying the pitch of a continuously-playing tone based on an average of recent values; the presentation of the cue depends in some way on user's cue configuration including whether to provide the cue at all.
